// Vendor the shared wl-web assets into this Astro project before dev/build.
//
// wl-web lives at the monorepo root (../../wl-web) — outside Astro's project root, which Vite will
// not serve from and `public/` cannot reference. Rather than fight that with fs.allow rules and
// inline-script gymnastics, we copy. Attune vendors the same two files the same way (CMake, at
// configure time), so both consumers have one story: wl-web is the source, everyone else takes a
// build-time copy.
//
// The copies are GENERATED and gitignored. Never edit them — edit ../../wl-web/ and re-run.
import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const WL_WEB = resolve(here, '../../../wl-web');

const BANNER =
  '/* GENERATED by tools/vendor.mjs from wl-web/ — DO NOT EDIT. Edit the source and re-run. */\n';

const jobs = [
  { from: 'wl-tokens.css', to: resolve(here, '../src/styles/wl-tokens.css'), banner: true },
  { from: 'wl-plot.js', to: resolve(here, '../public/wl/wl-plot.js'), banner: false },
  // Second copy of the tokens, served at /wl/wl-tokens.css. The hand-written pages (index.html,
  // /design-review, /404) have no build step and cannot import — they <link> to this.
  { from: 'wl-tokens.css', to: resolve(here, '../public/wl/wl-tokens.css'), banner: true },
];

if (!existsSync(WL_WEB)) {
  console.error(
    `\n  wl-web not found at ${WL_WEB}\n` +
      `  This project expects the monorepo layout (warren-labs/wl-web + warren-labs/warrenlabs-site).\n`
  );
  process.exit(1);
}

for (const job of jobs) {
  const src = resolve(WL_WEB, job.from);
  await mkdir(dirname(job.to), { recursive: true });
  if (job.banner) {
    const { readFile } = await import('node:fs/promises');
    await writeFile(job.to, BANNER + (await readFile(src, 'utf8')));
  } else {
    await copyFile(src, job.to);
  }
  console.log(`  vendored  wl-web/${job.from}`);
}
