// Vendor the shared wl-web assets into this Astro project before dev/build.
//
// wl-web lives at the monorepo root (../../wl-web) — outside Astro's project root, which Vite will
// not serve from and `public/` cannot reference. Rather than fight that with fs.allow rules and
// inline-script gymnastics, we copy. Attune vendors the same two files the same way (CMake, at
// configure time), so both consumers have one story: wl-web is the source, everyone else takes a
// build-time copy.
//
// The copies are GENERATED and gitignored. Never edit them — edit ../../wl-web/ and re-run.
//
// ---------------------------------------------------------------------------------------------
// CONTENT-HASHED FILENAMES, and why they are not optional here.
//
// The hand-written pages <link> these files directly (no bundler), so they used to load a stable
// `/wl/wl-tokens.css` that browsers cached indefinitely. That produced a bug nastier than "stale
// styles": when the OS-preference light block was removed, the retired rule
// `:root:not([data-theme='dark'])` had specificity (0,2,0) while its replacement `:root` has
// (0,1,0). A cached copy of the OLD file therefore BEAT the new one regardless of load order —
// appending a fresh stylesheet could not override it, and the site kept rendering light on a
// light-preferring OS for anyone with a warm cache.
//
// Specificity means you cannot fix a stale stylesheet by shipping a new one. The filename has to
// change. Astro's own pages were always safe (Vite hashes `_astro/*`); this brings the un-bundled
// surfaces up to the same guarantee.
import { mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const WL_WEB = resolve(here, '../../../wl-web');
const PUBLIC_WL = resolve(here, '../public/wl');

const BANNER =
  '/* GENERATED by tools/vendor.mjs from wl-web/ — DO NOT EDIT. Edit the source and re-run. */\n';

if (!existsSync(WL_WEB)) {
  console.error(
    `\n  wl-web not found at ${WL_WEB}\n` +
      `  This project expects the monorepo layout (warren-labs/wl-web + warren-labs/warrenlabs-site).\n`
  );
  process.exit(1);
}

const hash8 = (text) => createHash('sha256').update(text).digest('hex').slice(0, 8);

// Wipe public/wl so old hashed files can't accumulate — sync.mjs republishes the whole directory,
// so anything left here would be left on the live site forever.
await rm(PUBLIC_WL, { recursive: true, force: true });
await mkdir(PUBLIC_WL, { recursive: true });

// 1. Tokens for the ASTRO pages — imported by src/styles/tokens.css, so Vite bundles and hashes it
//    into _astro/. A stable filename is correct here; the bundler does the cache-busting.
{
  const src = await readFile(resolve(WL_WEB, 'wl-tokens.css'), 'utf8');
  const dest = resolve(here, '../src/styles/wl-tokens.css');
  await mkdir(dirname(dest), { recursive: true });
  await writeFile(dest, BANNER + src);
  console.log('  vendored  wl-tokens.css -> src/styles/  (Vite hashes this one)');
}

// 2. Hashed public copies for the surfaces with NO bundler: the hand-written pages, and the
//    inline <script> on /graphs.
const manifest = {};
for (const [key, file, banner] of [
  ['tokens', 'wl-tokens.css', true],
  ['plot', 'wl-plot.js', false],
]) {
  const raw = await readFile(resolve(WL_WEB, file), 'utf8');
  const body = banner ? BANNER + raw : raw;
  const hashed = file.replace(/\.(css|js)$/, `.${hash8(body)}.$1`);
  await writeFile(resolve(PUBLIC_WL, hashed), body);
  manifest[key] = `/wl/${hashed}`;
  console.log(`  vendored  ${file} -> public/wl/${hashed}`);
}

// 3. The manifest, so consumers reference the hashed name instead of guessing it.
//    JSON rather than JS: tools/sync-chrome.mjs runs in plain Node (which needs an import
//    attribute for JSON modules, so it readFile+parses), while Vite imports it directly for
//    graphs.astro. Same split as nav.json / nav.js.
await writeFile(
  resolve(here, '../src/data/wl-assets.json'),
  JSON.stringify(manifest, null, 2) + '\n'
);
console.log('  wrote     src/data/wl-assets.json');
